import asyncio
import os
import json
import base64
import hashlib
import requests
from google import genai
from google.genai import types
from dotenv import load_dotenv

# Import our existing specialised agents
from audio_agent import generate_audio_async

load_dotenv(os.path.join(os.path.dirname(__file__), '.env'))

class CreativeDirectorAgent:
    """
    An agent that thinks and creates like a creative director, seamlessly weaving 
    together text, images, and audio in a single, fluid output stream.
    Leverages Gemini's native interleaved multimodal capabilities.
    """
    def __init__(self):
        # We use the primary key for the Director Agent
        self.api_key = os.environ.get("GEMINI_API_KEY_1")
        if not self.api_key:
            raise ValueError("GEMINI_API_KEY_1 is missing.")
        # Using the new SDK client for multimodal generation
        self.client = genai.Client(api_key=self.api_key)
        self.infip_key = os.environ.get("INFIP_API_KEY")
        self.image_semaphore = asyncio.Semaphore(5) # Higher limit for faster throughput

    async def generate_mixed_media_stream(self, prompt: str, voice: str = "female"):
        """
        Orchestrates the creation of a fluid output stream where text and visuals
        are natively generated by Gemini 2.0.
        """
        style = "Cinematic Storybook"
        
        # Mapping voices for internal prompting
        voice_desc = "soft, warm female (Nova)" if voice == "female" else "deep, resonant male (Orion)"
        
        sys_prompt = f"""
        Role: World-Class Multimodal Creative Director & Storyteller.
        Format: {style}.
        Voice: {voice_desc}.
        
        CRITICAL MULTIMODAL GUIDELINES:
        - Generate EXACTLY 3-4 scenes based on the user's prompt.
        - Style: Ghibli-esque meets Cinematic Pixar - highly detailed, magical lighting.
        
        STRICT OUTPUT RULE:
        You are a storyboard artist. You MUST interleave your text. 
        EVERY SINGLE SCENE must follow this exact structure:
        1. An image prompt: [IMAGE_PROMPT: detailed visual description for this specific part of the story]
        2. The matching narrative text: (2-3 sentences of story)
        
        DO NOT write the whole story first and then the images. 
        DO NOT skip the [IMAGE_PROMPT: ...] tags.
        
        Example:
        [IMAGE_PROMPT: A majestic white dragon soaring through purple clouds at sunset.]
        The dragon's scales shimmered like opals as it banked through the velvet clouds. Below, the kingdom of Aetheria began to glow with the first lamps of evening.
        """

        from story_agent import GEMINI_API_KEYS
        import time
        
        # Models to try in order - each has its own separate quota pool
        MODELS_TO_TRY = [
            'gemini-2.5-flash',
            'gemini-2.5-pro',
            'gemini-2.0-flash',
            'gemini-2.0-flash-lite',
        ]
        
        print(f"🎬 Creative Director is generating multimodal story: {prompt}")
        
        if not GEMINI_API_KEYS:
            print("❌ Director encountered an error: No API Keys available")
            return []
        
        # Try each key with each model - smart cascading fallback
        for i, api_key in enumerate(GEMINI_API_KEYS):
            # Key 10 was reported as expired in logs, but we still try it just in case of transient issues
            client = genai.Client(api_key=api_key)
            
            for model_name in MODELS_TO_TRY:
                # Ensure model name has the models/ prefix which is safer across API versions
                full_model_name = f"models/{model_name}" if not model_name.startswith("models/") else model_name
                
                try:
                    print(f"🎬 Trying Key {i+1} with model '{full_model_name}'...")
                    
                    # Use the proper GenerateContentConfig for system instructions
                    response = client.models.generate_content(
                        model=full_model_name,
                        contents=prompt,
                        config=types.GenerateContentConfig(
                            system_instruction=sys_prompt,
                            temperature=0.7
                        )
                    )
                    
                    if not response or not response.text:
                        raise ValueError("Empty response from AI")
                        
                    print(f"✅ Success with Key {i+1} on model '{full_model_name}'!")
                    return await self._process_simulated_interleaved(response.text, voice)

                except Exception as e:
                    err_str = str(e).lower()
                    print(f"⚠️ Failed Key {i+1} / {model_name}: {err_str[:120]}")
                    
                    # Special handling for specific error types
                    if "401" in err_str or "403" in err_str or "expired" in err_str:
                        print(f"   → Key {i+1} authentication failure, skipping to next key...")
                        break # Go to next key
                        
                    if "429" in err_str:
                        # 429 is often per-model, so we try the next model on the same key
                        continue 
                        
            # If we reach here, all models on this key failed
            if i < len(GEMINI_API_KEYS) - 1:
                print(f"🎬 Key {i+1} exhausted. Cooling down for 5s before switching to Key {i+2}...")
                await asyncio.sleep(5) # Small backoff to avoid cascading rate limits
                
        # If all keys and models exhausted
        print("❌ All configured Gemini API keys and models exhausted.")
        return []

    async def _process_simulated_interleaved(self, full_text: str, voice: str):
        import re
        import urllib.parse
        import requests
        import asyncio
        from audio_agent import generate_audio_async
        
        nodes = []
        story_parts = []
        
        print(f"📝 Processor received raw story of length: {len(full_text)}")
        
        # 1. Clean the text and attempt broad segment splitting
        # Catching: [IMAGE_PROMPT: ...], (IMAGE_PROMPT: ...), **IMAGE_PROMPT: ...**
        # More robust regex to handle variations in spacing and bolding
        raw_segments = re.split(r'[*_]{0,2}[(\[]\s*IMAGE_PROMPT\s*[:\-]?\s*(.*?)\s*[)\]][*_]{0,2}', full_text, flags=re.IGNORECASE)
        
        # Handle cases where segments are too few (fallback to paragraph splitting)
        if len(raw_segments) <= 1:
            print("📝 Standard tags missing, falling back to Paragraph splitting...")
            para_segments = [p.strip() for p in re.split(r'\n\n+', full_text) if p.strip()]
            final_segments = [""] # Initial lead text placeholder
            for p in para_segments:
                # Interleaved alignment: [TextAtStart, Img1, Text1, Img2, Text2...]
                final_segments.append(p[:250]) # Image Prompt (using start of paragraph)
                final_segments.append(p)       # Narrative Content
        else:
            final_segments = raw_segments

        # 2. Extract pairs of (Image Description, Narrative Text)
        pending_image_tasks = []
        
        # Initial lead text (if any)
        if final_segments[0].strip():
            lead_text = final_segments[0].strip()
            story_parts.append(lead_text)
            nodes.append({"id": 1, "type": "text", "content": lead_text})

        # Process segments in pairs
        # Structure: [lead_text, img1, text1, img2, text2...]
        for i in range(1, len(final_segments), 2):
            img_desc = final_segments[i].strip()
            text_desc = final_segments[i+1].strip() if i+1 < len(final_segments) else ""
            
            # Create text node if text exists
            if text_desc:
                story_parts.append(text_desc)
                nodes.append({"id": len(nodes) + 1, "type": "text", "content": text_desc})
            
            # Queue image generation
            if img_desc:
                # We record WHERE to insert this image in the nodes list using an index placeholder
                placeholder_idx = len(nodes)
                pending_image_tasks.append((placeholder_idx, img_desc))

        # 3. Generate ALL images concurrently for massive speedup
        if pending_image_tasks:
            print(f"🖼️ Parallelizing {len(pending_image_tasks)} image generation tasks...")
            
            # Prepare concurrency
            async def generate_and_return(idx_info, desc):
                async with self.image_semaphore:
                    node = await self._generate_pollinations_image(desc)
                    return idx_info, node

            gen_tasks = [generate_and_return(t[0], t[1]) for t in pending_image_tasks]
            results = await asyncio.gather(*gen_tasks)
            
            # Sort results by index in reverse to insert correctly without shifting future indices
            results.sort(key=lambda x: x[0], reverse=True)
            for target_idx, img_node in results:
                if img_node:
                    nodes.insert(target_idx, img_node)

        # 4. Final numbering clean up
        for i, node in enumerate(nodes):
            node["id"] = i + 1

        # 5. Generate Audio for the total combined story
        story_text = "\n\n".join(story_parts).strip()
        if story_text:
            audio_url = await generate_audio_async(story_text, voice)
            if nodes:
                # Attach global audio to the first node
                nodes[0]["audio_url"] = audio_url
        
        print(f"✅ Interleaved Process Complete: {len(nodes)} nodes constructed.")
        return nodes

    async def _generate_pollinations_image(self, img_desc: str):
        """Generate a single image via Pollinations AI. Executes via thread to avoid blocking."""
        import urllib.parse
        import asyncio
        import os
        
        def _sync_fetch():
            log_file = "image_gen_debug.log"
            import time
            import random
            
            def get_keywords(text):
                # Simple logic to extract potential keywords for fallback search
                words = [w.strip(" ,.!?\"") for w in text.lower().split() if len(w) > 3]
                # Filter common stop words manually to keep it lightweight
                stops = {"this", "that", "with", "from", "their", "into", "onto", "under", "above", "style", "cinematic", "highly", "detailed", "render", "pixar", "vibrant", "lighting"}
                keywords = [w for w in words if w not in stops]
                return ",".join(keywords[:3]) if keywords else "nature"

            for attempt in range(4): # Restricted to INFIP priority + safe fallback
                content = None
                try:
                    seed = random.randint(1, 1000000)
                    encoded = urllib.parse.quote(img_desc[:400])
                    keywords = get_keywords(img_desc)
                    
                    msg = f"🖼️ [Scene Gen] Attempt {attempt+1} for: {img_desc[:30]}..."
                    print(msg, flush=True) # Direct console feedback
                    with open(log_file, "a", encoding="utf-8") as log:
                        log.write(f"DEBUG: {msg}\n")
                        log.flush()
                    
                    if self.infip_key and attempt < 2:
                        # Attempt 1-2: INFIP API (Primary Premium Provider)
                        try:
                            msg_infip = f"🖼️ [Scene Gen] INFIP Priority Attempt {attempt+1}..."
                            print(msg_infip, flush=True)
                            
                            # Use the official API domain as per infip.pro documentation
                            # Rotating between api.infip.pro and chat.infip.pro to ensure reachability
                            domains = ["api.infip.pro", "chat.infip.pro"]
                            infip_url = f"https://{domains[attempt % 2]}/v1/images/generations"
                            
                            headers = {
                                "Authorization": f"Bearer {self.infip_key}",
                                "Content-Type": "application/json",
                                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
                            }
                            # 'flux-schnell' is officially listed on their models page
                            payload = {
                                "prompt": img_desc,
                                "model": "flux-schnell", 
                                "n": 1,
                                "size": "1024x1024",
                                "response_format": "url"
                            }
                            resp = requests.post(infip_url, json=payload, headers=headers, timeout=60)
                            
                            with open(log_file, "a", encoding="utf-8") as log:
                                log.write(f"DEBUG: INFIP [Attempt {attempt+1}] HTTP {resp.status_code}\n")
                                if resp.status_code == 200:
                                    try:
                                        data = resp.json()
                                        log.write(f"DEBUG: INFIP Success Data keys: {list(data.keys())}\n")
                                        
                                        # Standard format is data[0].url
                                        if "data" in data and len(data["data"]) > 0:
                                            img_url = data["data"][0].get("url")
                                            if img_url:
                                                log.write(f"DEBUG: Found URL: {img_url}\n")
                                                img_resp = requests.get(img_url, timeout=35)
                                                if img_resp.status_code == 200:
                                                    content = img_resp.content
                                                    log.write(f"DEBUG: Downloaded image, size: {len(content)}\n")
                                        # Fallback for non-standard JSON
                                        elif "url" in data:
                                            img_url = data["url"]
                                            img_resp = requests.get(img_url, timeout=35)
                                            if img_resp.status_code == 200:
                                                content = img_resp.content
                                        elif "image" in data: # Base64
                                            content = base64.b64decode(data["image"])
                                    except Exception as je:
                                        log.write(f"DEBUG: INFIP JSON error: {str(je)}\n")
                                else:
                                    log.write(f"DEBUG: INFIP Error Body: {resp.text[:200]}\n")
                                log.flush()
                        except Exception as e:
                            with open(log_file, "a", encoding="utf-8") as log:
                                log.write(f"DEBUG: INFIP Exception: {str(e)}\n")
                                log.flush()
                        
                        if not content:
                            if attempt == 0: time.sleep(5) # Wait a bit before second attempt
                            continue

                    elif attempt == 2:
                        # Attempt 3: Contextual Fallback (LoremFlickr) - SILENT SAFETY
                        try:
                            l_url = f"https://loremflickr.com/1024/1024/{keywords}?random={seed}"
                            resp = requests.get(l_url, timeout=25, allow_redirects=True)
                            if resp.status_code == 200 and len(resp.content) > 15000:
                                content = resp.content
                            else:
                                continue
                        except:
                            continue
                    else:
                        # Attempt 4: Final Safety
                        try:
                            unique_id = os.urandom(8).hex()
                            p_url = f"https://picsum.photos/seed/{unique_id}/1024/1024"
                            resp = requests.get(p_url, timeout=25)
                            if resp.status_code == 200:
                                content = resp.content
                            else:
                                continue
                        except:
                            continue

                    # If we have content (from any attempt), save and return
                    if content:
                        filename = f"scene_{os.urandom(4).hex()}.jpg"
                        save_dir = os.path.join("static", "images")
                        os.makedirs(save_dir, exist_ok=True)
                        save_path = os.path.join(save_dir, filename)
                        with open(save_path, "wb") as f:
                            f.write(content)
                        
                        success_msg = f"✅ Saved {filename} on attempt {attempt+1}"
                        print(success_msg, flush=True)
                        with open(log_file, "a", encoding="utf-8") as log:
                            log.write(f"DEBUG: {success_msg}\n")
                            log.flush()
                        return f"/static/images/{filename}"
                            
                except Exception as e:
                    with open(log_file, "a", encoding="utf-8") as log:
                        log.write(f"DEBUG: ERROR on Attempt {attempt+1}: {str(e)}\n")
                        log.flush()
            
            return None
        img_url = await asyncio.to_thread(_sync_fetch)
        
        if img_url:
            return {"type": "image", "image_url": img_url}
        return None

    async def _generate_node_audio(self, node: dict, text: str):
        """Helper to generate audio for a narrative node."""
        audio_url = await generate_audio_async(text)
        node["audio_url"] = audio_url

    async def _execute_timeline(self, timeline: list):
        """
        Takes the Director's mapped timeline and executes the generation of 
        assets (audio and images) in parallel for maximum fluidity and speed.
        """
        tasks = []
        for node in timeline:
            task = self._produce_node_assets(node)
            tasks.append(task)
            
        # Wait for all mixed-media elements to be created
        completed_nodes = await asyncio.gather(*tasks)
        print("🎬 All mixed-media assets have been generated and interleaved successfully.")
        return completed_nodes

    async def _produce_node_assets(self, node: dict):
        """
        Produces the actual physical media files for a specific node in the timeline.
        This seamlessly weaves the text, audio, and visual generation together.
        """
        node_id = node.get("id", "0")
        
        # Define the generation logic (using threading for synchronous agent calls)
        # Note: The older image generation agent is deprecated in favor of direct Pollinations generation above

        # We use existing agents as backup or secondary production logic
        from audio_agent import generate_audio_async
        audio_path = await generate_audio_async(node.get("narration", ""))
        
        # Image generation has shifted to the interleaving phase
        image_path = node.get("image_url", "")
        return {
            "id": node_id,
            "text": node.get("narration", ""),
            "audio_url": audio_path,
            "image_url": image_path,
            "on_screen_text": node.get("on_screen_text", "")
        }

# Example usage trigger
if __name__ == "__main__":
    director = CreativeDirectorAgent()
    vision = "A cinematic marketing explainer about a futuristic smart-home AI."
    # asyncio.run(director.generate_mixed_media_stream(vision, style="marketing asset generator"))
